### PR TITLE
Changed more codelists to opensafely ones

### PR DESCRIPTION
**Pull request by NikNakk**
Moved most of the remaining codelists to the published opensafely ones, as discussed on call on 31/03/2021.

### CODE REVIEW

**Comment by AnnaB45** [comment]
@NikNakk I think there are four more codelists that need to be switched over to the OpenSAFELY codelists version:
* [Methotrexate - primary care](https://codelists.opensafely.org/codelist/opensafely/methotrexate-oral/738b5e12/)
* [Sulfasalazine](https://codelists.opensafely.org/codelist/opensafely/sulfasalazine-oral/285d0473/)
* [Mesalazine](https://codelists.opensafely.org/builder/1ba5f834/)
* [Ankylosing spondylitis](https://codelists.opensafely.org/codelist/user/mark-yates/axial-spondyloarthritis/3da730d4/#tree) - codelist confirmed by James on this [issue](https://github.com/opensafely/immunosuppressant-meds-research/issues/3)

**Comment by NikNakk** [comment]
Ok @AnnaB45 have done all except methotrexate; the methotrexate csv file seems to be missing headers so I can't use it. Also not sure how we're handling oral + injectable primary care methotrexate codelists.

The error in the test runner seems to be happening in master too, so isn't related to changes in this branch.

**Comment by AnnaB45** [comment]
@NikNakk I've added another commit to:
* Update most of the primary care medication codelists so using the dm+d version rather than bnf (on Brian's advice)
* Add in methotrexate-injectables, so it's included in the cohort - then need to make changes to stata code to include in the standard systemic group if required. I've also fixed the methotrexate-oral codelist on OpenSAFELY codelists so now includes headers.
Can you have a look through the additional changes and let me know if you're happy with them?

**Comment by NikNakk** [comment]
Thanks, that looks fine. Are we ok to merge the PR? It would be nice if the issue in master with the tnfmono job were fixed so that we could ensure the test passes first!

**Comment by AnnaB45** [comment]
Yeah - I think the error is due to the dummy data, for the tnf_mono group there aren't any patients in comparator population so model can't run. Not sure how to fix this, but I've done some locally testing on the other models and all the others seem to run fine.

**Pull request merged**
