### PR TITLE
Adding in high cost drugs

### PR DESCRIPTION
**Pull request by AnnaB45**
Adding in high cost drugs to the study definition and uploaded the immunosuppressants code list.
I've made these changes on a branch from the master file - I think there may be other changes Nick has made that haven't yet been merged on to the master file.

### CODE REVIEW

**Comment by NikNakk** [comment]
Thanks for the update. However, this doesn't match the way we're analysing the data. @myatesrheum has now split the immunosuppressant file into 21 separate files by drug or group of drugs as we need them for the analysis. I've also updated the code in my fork to use these data. However, at present there are a number of problematic drug names which include characters like % that seem to throw 'Value contains disallowed characters' errors when cohort extractor runs. I'll need to do more work on this. Anyway, I would suggest this pull request is closed without merging since it doesn't do what we need.

**Comment by brianmackenna** [comment]
Sorry to come to this slightly late I'm just going to reopen for discussion until we resolve as I think there are a few issues going on (and may require issues in other repos)

>  there are a number of problematic drug names which include characters like % that seem to throw 'Value contains disallowed characters' errors when cohort extractor runs

 @evansd does this potentially need tinkering in the `chort_extractor` or do we need to take different approach with certain characters?


> @myatesrheum has now split the immunosuppressant file into 21 separate files by drug

@myatesrheum  are you able to share these on the issues for documentation / checking if not complete?

@inglesp ^these files are essentially codelists. @myatesrheum (and team?) have done a great job and created [files](https://github.com/opensafely/immunosuppressant-meds-research/issues/29) which are strings that align or resemble multiple different ways of (mis)spelling a medicine and its brand. This can be queried by the `cohort_extractor`. Just been chatting with @evansd and although they are codelists for purposes of our work they aren't really codelist. Do you think we should keep them on OpenCodelists for transparency and re-use or should manage in a different way?

**Comment by inglesp** [comment]
> Do you think we should keep them on OpenCodelists for transparency and re-use or should manage in a different way?

My gut feeling is that we shouldn't host them on OpenCodelists, since they're very different to the kind of codelist we're dealing with now, and that will require more work to support.  

Hosting CSV files on GitHub should work -- would they belong better in a study repo (so that they're near the code) or in a separate repo (so that they can be reused by other research)?

**Comment by NikNakk** [comment]
They’re going to be needed for anything that uses the high cost drug data. They’re used in exactly the same way as the code lists with respect to the cohort_extractor code, but I agree that they aren’t actually a code list per se. Would they make sense as a submodule? Or can the cohort extractor’s update code list functionality be extended to cover something like this? Or are we then just reinventing the wheel and better off putting them up as codelists after all?

Nick
________________________________

**Comment by inglesp** [comment]
Thinking about this some more, I reckon we can tweak OpenCodelists to also be a dumb CSV server, so you could host arbitrary CSVs.  That way, OpenSAFELY studies that use the high cost drug data could treat them as codelists as normal.

**Comment by brianmackenna** [comment]
If you think viable @inglesp Could we perhaps restrict in some way to ensure it doesn't become dumping ground for dumb csvs? e.g. you could upload only?

**Pull request closed without merging**
