### PR TITLE
Updates to parallelise cox model runs

### PR DESCRIPTION
**Pull request by AnnaB45**
Updates to cox model (201_cox_models.do) to limit run to 1st Sept 2020 and remove one of the loops from STATA code and parallelise in project.yaml code instead.
Updates to survival code (301_survival_curves.do) to limit run to 1st September 2020.
Updates to project.yaml file to parallelise cox model runs.

### CODE REVIEW

**Review by jamesgalloway — APPROVED** [review]

**Comment by jamesgalloway** [comment]
Can I ask for one change to the prepare data file?

Might be easier to get you to add in?



From: AnnaB45 ***@***.***>
Date: Friday, 26 March 2021 at 16:15
To: opensafely/immunosuppressant-meds-research ***@***.***>
Cc: Galloway, James ***@***.***>, Review requested ***@***.***>
Subject: Re: [opensafely/immunosuppressant-meds-research] Updates to parallelise cox model runs (#94)

@AnnaB45<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnnaB45&data=04%7C01%7Cjames.galloway%40kcl.ac.uk%7C7495e5695da4494c17dc08d8f0724e3e%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637523721011944789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t6JuT%2BAgMNdMmO%2Bu0rA0S%2FEFP9fS9nnU7ZxVic5CK8s%3D&reserved=0> requested your review on: #94<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopensafely%2Fimmunosuppressant-meds-research%2Fpull%2F94&data=04%7C01%7Cjames.galloway%40kcl.ac.uk%7C7495e5695da4494c17dc08d8f0724e3e%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637523721011944789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iObmAv%2FzqUuPWBjq8IlxLBS1Vrygp0iaoqgLRf33l5g%3D&reserved=0> Updates to parallelise cox model runs.

**Comment by jamesgalloway** [comment]
We need to add the following after line 699 in the 000_define_covariates.do

foreach var in standtnf standtnf3m tnfmono standil6 standil17 standil23 standjaki standritux  {

                recode `var' 0=. if imiddrugcategory ==1

}

From: AnnaB45 ***@***.***>
Date: Friday, 26 March 2021 at 16:15
To: opensafely/immunosuppressant-meds-research ***@***.***>
Cc: Galloway, James ***@***.***>, Review requested ***@***.***>
Subject: Re: [opensafely/immunosuppressant-meds-research] Updates to parallelise cox model runs (#94)

@AnnaB45<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnnaB45&data=04%7C01%7Cjames.galloway%40kcl.ac.uk%7C7495e5695da4494c17dc08d8f0724e3e%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637523721011944789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t6JuT%2BAgMNdMmO%2Bu0rA0S%2FEFP9fS9nnU7ZxVic5CK8s%3D&reserved=0> requested your review on: #94<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopensafely%2Fimmunosuppressant-meds-research%2Fpull%2F94&data=04%7C01%7Cjames.galloway%40kcl.ac.uk%7C7495e5695da4494c17dc08d8f0724e3e%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637523721011944789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iObmAv%2FzqUuPWBjq8IlxLBS1Vrygp0iaoqgLRf33l5g%3D&reserved=0> Updates to parallelise cox model runs.

**Comment by AnnaB45** [comment]
@jamesgalloway yes - I'll make that update to the 000_define_covariates.do file now

**Comment by jamesgalloway** [comment]
😊

From: AnnaB45 ***@***.***>
Date: Friday, 26 March 2021 at 16:29
To: opensafely/immunosuppressant-meds-research ***@***.***>
Cc: Galloway, James ***@***.***>, Mention ***@***.***>
Subject: Re: [opensafely/immunosuppressant-meds-research] Updates to parallelise cox model runs (#94)

@jamesgalloway<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjamesgalloway&data=04%7C01%7Cjames.galloway%40kcl.ac.uk%7Cd6c33c51df5e47676dff08d8f0745be7%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637523729864330542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U0HZe%2BxhiXeH72e%2FVUhoFnMQCDipPpseYAtwmBnAhpQ%3D&reserved=0> yes - I'll make that update to the 000_define_covariates.do file now

**Review by alexwalkerepi — APPROVED** [review]
Yes this looks like how I was imagining doing the parallelisation :)

Incidentally (not for now but later) - I'd suggest adding the `logs/` and `metadata/` directories to the `.gitignore` and removing the logs that are there. They don't really need to be committed to the repo and it will reduce the number of unnecessary files when reviewing.

**Comment by AnnaB45** [comment]
The check is failing here but I think due to dummy data rather than any coding error (one of the cox model fails because all the population that die are on the medicine of interest so no population to compare to)

**Pull request merged**
